# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: arango.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'arango.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x61rango.proto\x12\x06\x61rango\"\x81\x01\n\x0bSaveRequest\x12\x12\n\ncollection\x18\x01 \x01(\t\x12/\n\x06\x66ields\x18\x02 \x03(\x0b\x32\x1f.arango.SaveRequest.FieldsEntry\x1a-\n\x0b\x46ieldsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\";\n\x0cSaveResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t\"-\n\nGetRequest\x12\x12\n\ncollection\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x02 \x01(\t\"|\n\x0bGetResponse\x12/\n\x06\x66ields\x18\x01 \x03(\x0b\x32\x1f.arango.GetResponse.FieldsEntry\x12\r\n\x05\x65rror\x18\x02 \x01(\t\x1a-\n\x0b\x46ieldsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"4\n\x10StreamGetRequest\x12\x12\n\ncollection\x18\x01 \x01(\t\x12\x0c\n\x04keys\x18\x02 \x03(\t2\xa9\x02\n\rArangoService\x12\x31\n\x04Save\x12\x13.arango.SaveRequest\x1a\x14.arango.SaveResponse\x12.\n\x03Get\x12\x12.arango.GetRequest\x1a\x13.arango.GetResponse\x12<\n\tStreamGet\x12\x18.arango.StreamGetRequest\x1a\x13.arango.GetResponse0\x01\x12\x39\n\nStreamSave\x12\x13.arango.SaveRequest\x1a\x14.arango.SaveResponse(\x01\x12<\n\x0bStreamBatch\x12\x13.arango.SaveRequest\x1a\x14.arango.SaveResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'arango_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SAVEREQUEST_FIELDSENTRY']._loaded_options = None
  _globals['_SAVEREQUEST_FIELDSENTRY']._serialized_options = b'8\001'
  _globals['_GETRESPONSE_FIELDSENTRY']._loaded_options = None
  _globals['_GETRESPONSE_FIELDSENTRY']._serialized_options = b'8\001'
  _globals['_SAVEREQUEST']._serialized_start=25
  _globals['_SAVEREQUEST']._serialized_end=154
  _globals['_SAVEREQUEST_FIELDSENTRY']._serialized_start=109
  _globals['_SAVEREQUEST_FIELDSENTRY']._serialized_end=154
  _globals['_SAVERESPONSE']._serialized_start=156
  _globals['_SAVERESPONSE']._serialized_end=215
  _globals['_GETREQUEST']._serialized_start=217
  _globals['_GETREQUEST']._serialized_end=262
  _globals['_GETRESPONSE']._serialized_start=264
  _globals['_GETRESPONSE']._serialized_end=388
  _globals['_GETRESPONSE_FIELDSENTRY']._serialized_start=109
  _globals['_GETRESPONSE_FIELDSENTRY']._serialized_end=154
  _globals['_STREAMGETREQUEST']._serialized_start=390
  _globals['_STREAMGETREQUEST']._serialized_end=442
  _globals['_ARANGOSERVICE']._serialized_start=445
  _globals['_ARANGOSERVICE']._serialized_end=742
# @@protoc_insertion_point(module_scope)
