# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import arango_pb2 as arango__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in arango_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ArangoServiceStub(object):
    """Сервис для работы с ArangoDB
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Save = channel.unary_unary(
                '/arango.ArangoService/Save',
                request_serializer=arango__pb2.SaveRequest.SerializeToString,
                response_deserializer=arango__pb2.SaveResponse.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/arango.ArangoService/Get',
                request_serializer=arango__pb2.GetRequest.SerializeToString,
                response_deserializer=arango__pb2.GetResponse.FromString,
                _registered_method=True)
        self.StreamGet = channel.unary_stream(
                '/arango.ArangoService/StreamGet',
                request_serializer=arango__pb2.StreamGetRequest.SerializeToString,
                response_deserializer=arango__pb2.GetResponse.FromString,
                _registered_method=True)
        self.StreamSave = channel.stream_unary(
                '/arango.ArangoService/StreamSave',
                request_serializer=arango__pb2.SaveRequest.SerializeToString,
                response_deserializer=arango__pb2.SaveResponse.FromString,
                _registered_method=True)
        self.StreamBatch = channel.stream_stream(
                '/arango.ArangoService/StreamBatch',
                request_serializer=arango__pb2.SaveRequest.SerializeToString,
                response_deserializer=arango__pb2.SaveResponse.FromString,
                _registered_method=True)


class ArangoServiceServicer(object):
    """Сервис для работы с ArangoDB
    """

    def Save(self, request, context):
        """Синхронное сохранение документа
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Синхронное получение документа
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamGet(self, request, context):
        """Потоковое получение документов (server streaming)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamSave(self, request_iterator, context):
        """Потоковое сохранение документов (client streaming)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamBatch(self, request_iterator, context):
        """Двунаправленный поток (bidirectional streaming)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ArangoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Save': grpc.unary_unary_rpc_method_handler(
                    servicer.Save,
                    request_deserializer=arango__pb2.SaveRequest.FromString,
                    response_serializer=arango__pb2.SaveResponse.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=arango__pb2.GetRequest.FromString,
                    response_serializer=arango__pb2.GetResponse.SerializeToString,
            ),
            'StreamGet': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamGet,
                    request_deserializer=arango__pb2.StreamGetRequest.FromString,
                    response_serializer=arango__pb2.GetResponse.SerializeToString,
            ),
            'StreamSave': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamSave,
                    request_deserializer=arango__pb2.SaveRequest.FromString,
                    response_serializer=arango__pb2.SaveResponse.SerializeToString,
            ),
            'StreamBatch': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamBatch,
                    request_deserializer=arango__pb2.SaveRequest.FromString,
                    response_serializer=arango__pb2.SaveResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'arango.ArangoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('arango.ArangoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ArangoService(object):
    """Сервис для работы с ArangoDB
    """

    @staticmethod
    def Save(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arango.ArangoService/Save',
            arango__pb2.SaveRequest.SerializeToString,
            arango__pb2.SaveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arango.ArangoService/Get',
            arango__pb2.GetRequest.SerializeToString,
            arango__pb2.GetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamGet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/arango.ArangoService/StreamGet',
            arango__pb2.StreamGetRequest.SerializeToString,
            arango__pb2.GetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamSave(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/arango.ArangoService/StreamSave',
            arango__pb2.SaveRequest.SerializeToString,
            arango__pb2.SaveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamBatch(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/arango.ArangoService/StreamBatch',
            arango__pb2.SaveRequest.SerializeToString,
            arango__pb2.SaveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
